# Generated by Django 3.2.5 on 2022-03-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='유저ID')),
                ('user_password', models.CharField(max_length=20, verbose_name='유저비밀번호')),
                ('user_type', models.IntegerField(verbose_name='유저타입')),
                ('user_email', models.EmailField(max_length=100, verbose_name='유저이메일')),
                ('user_phonenum', models.CharField(max_length=15, verbose_name='유저전화번호')),
            ],
        ),
    ]
